replicaCount: 1

image:
  repository: your-dockerhub-username/microcks-hub
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5173
  nodePort: 30173

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []
